name:                magic-maze
version:             0.1.0.0
github:              "karshan/magic-maze"
license:             WTFPL
author:              "Karshan Sharma"
maintainer:          "karshan.sharma@gmail.com"
copyright:           "2018 Karshan Sharma"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         TODO

executables:
  magic-maze-backend:
    main:                Main.hs
    source-dirs:         backend
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - aeson
    - http-types
    - protolude
    - wai
    - wai-app-static
    - wai-websockets
    - warp
    - websockets
